services:
  postgres:
    env_file:
      - .env
    image: postgres:15-alpine
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    container_name: "postgres"
  redis:
    image: redis:7.2.0-alpine
    restart: always
    command: /bin/sh -c "exec redis-server --requirepass $$REDIS_HOST_PASSWORD"
    ports:
      - '6379:6379'
    env_file: .env
    container_name: "redis-server"
    volumes:
      - redis-data:/data
  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z
    restart: always
    command: server /data --console-address :9001
    ports:
      - '9001:9001'
      - '9000:9000'
    env_file: .env
    container_name: "minio"
    volumes:
      - minio-data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  playwright:
    image: mcr.microsoft.com/playwright:v1.49.0
    restart: always
    container_name: "playwright-e2e"
    init: true
    ipc: host
    command: [ "/bin/sh", -c, "cd /home/pwuser && npx -y playwright@1.49.0 run-server --port 5000" ]
    network_mode: host

volumes:
  postgres-vol:
  redis-data:
  minio-data:
